test_sources = \
	a1-image-sample.c 				\
	a1-mask.c					\
	a1-traps-sample.c				\
	a8-mask.c					\
	alpha-similar.c					\
	big-line.c					\
	big-trap.c					\
	bilevel-image.c					\
	caps.c						\
	caps-joins.c					\
	caps-joins-alpha.c				\
	caps-joins-curve.c				\
	caps-sub-paths.c				\
	clear.c						\
	clip-all.c					\
	clip-disjoint.c					\
	clip-empty.c					\
	clip-fill.c					\
	clip-fill-rule.c				\
	clip-fill-rule-pixel-aligned.c			\
	clip-fill-unbounded.c				\
	clip-image.c					\
	clip-nesting.c					\
	clip-operator.c					\
	clip-push-group.c				\
	clip-stroke.c					\
	clip-stroke-unbounded.c				\
	clip-text.c					\
	clip-twice.c					\
	clip-unbounded.c				\
	clip-zero.c					\
	clipped-group.c					\
	clipped-surface.c				\
	close-path.c					\
	close-path-current-point.c			\
	composite-integer-translate-source.c		\
	composite-integer-translate-over.c		\
	composite-integer-translate-over-repeat.c	\
	copy-path.c					\
	create-for-stream.c				\
	create-from-png.c				\
	create-from-png-stream.c			\
	culled-glyphs.c					\
	curve-to-as-line-to.c				\
	dash-caps-joins.c				\
	dash-curve.c					\
	dash-infinite-loop.c				\
	dash-no-dash.c					\
	dash-offset-negative.c				\
	dash-scale.c					\
	dash-state.c					\
	dash-zero-length.c				\
	degenerate-arc.c				\
	degenerate-curve-to.c				\
	degenerate-dash.c				\
	degenerate-path.c				\
	degenerate-pen.c				\
	degenerate-rel-curve-to.c			\
	device-offset.c					\
	device-offset-fractional.c			\
	device-offset-positive.c			\
	device-offset-scale.c				\
	extend-pad.c					\
	extend-pad-border.c				\
	extend-pad-similar.c				\
	extend-reflect.c				\
	extend-reflect-similar.c			\
	extend-repeat.c					\
	extend-repeat-similar.c				\
	extended-blend.c				\
	extended-blend-alpha.c				\
	fill-alpha.c					\
	fill-alpha-pattern.c				\
	fill-and-stroke.c				\
	fill-and-stroke-alpha.c				\
	fill-and-stroke-alpha-add.c			\
	fill-degenerate-sort-order.c			\
	fill-empty.c					\
	fill-image.c				        \
	fill-missed-stop.c				\
	fill-rule.c					\
	filter-bilinear-extents.c			\
	filter-nearest-offset.c				\
	filter-nearest-transformed.c			\
	finer-grained-fallbacks.c			\
	font-face-get-type.c				\
	font-matrix-translation.c			\
	font-options.c					\
	glyph-cache-pressure.c				\
	get-and-set.c					\
	get-clip.c					\
	get-group-target.c				\
	get-path-extents.c				\
	gradient-alpha.c				\
	gradient-constant-alpha.c			\
	gradient-zero-stops.c				\
	group-clip.c					\
	group-paint.c					\
	group-unaligned.c				\
	huge-linear.c					\
	huge-radial.c					\
	image-surface-source.c				\
	implicit-close.c				\
	infinite-join.c					\
	in-fill-empty-trapezoid.c			\
	in-fill-trapezoid.c				\
	invalid-matrix.c				\
	joins.c						\
	large-clip.c					\
	large-font.c					\
	large-source.c					\
	large-source-roi.c				\
	large-twin-antialias-mixed.c			\
	leaky-dash.c					\
	leaky-dashed-rectangle.c			\
	leaky-dashed-stroke.c				\
	leaky-polygon.c					\
	line-width.c					\
	line-width-scale.c				\
	line-width-zero.c				\
	linear-gradient.c				\
	linear-gradient-reflect.c			\
	long-dashed-lines.c				\
	long-lines.c					\
	mask.c						\
	mask-alpha.c					\
	mask-ctm.c					\
	mask-glyphs.c					\
	mask-surface-ctm.c				\
	mask-transformed-image.c			\
	mask-transformed-similar.c			\
	meta-surface-pattern.c				\
	mime-data.c					\
	miter-precision.c				\
	move-to-show-surface.c				\
	new-sub-path.c					\
	nil-surface.c					\
	operator.c					\
	operator-alpha.c				\
	operator-clear.c				\
	operator-source.c				\
	over-above-source.c				\
	over-around-source.c				\
	over-below-source.c				\
	over-between-source.c				\
	overlapping-glyphs.c				\
	paint.c						\
	paint-repeat.c					\
	paint-source-alpha.c				\
	paint-with-alpha.c				\
	path-append.c					\
	path-precision.c				\
	pattern-get-type.c				\
	pattern-getters.c				\
	pixman-rotate.c					\
	png.c						\
	push-group.c					\
	push-group-color.c				\
	radial-gradient.c				\
	random-intersections-eo.c			\
	random-intersections-nonzero.c			\
	random-intersections-curves-eo.c		\
	random-intersections-curves-nz.c		\
	rectangle-rounding-error.c			\
	rectilinear-fill.c				\
	rectilinear-miter-limit.c			\
	rectilinear-dash.c				\
	rectilinear-stroke.c				\
	reflected-stroke.c				\
	rel-path.c					\
	rgb24-ignore-alpha.c				\
	rotate-image-surface-paint.c			\
	rotated-clip.c					\
	scale-down-source-surface-paint.c		\
	scale-offset-image.c				\
	scale-offset-similar.c				\
	scale-source-surface-paint.c			\
	scaled-font-zero-matrix.c			\
	stroke-ctm-caps.c				\
	stroke-image.c				        \
	select-font-face.c				\
	select-font-no-show-text.c			\
	self-copy.c					\
	self-copy-overlap.c				\
	self-intersecting.c				\
	set-source.c					\
	show-glyphs-many.c				\
	show-text-current-point.c			\
	skew-extreme.c					\
	smask.c						\
	smask-fill.c					\
	smask-image-mask.c				\
	smask-mask.c					\
	smask-paint.c					\
	smask-stroke.c					\
	smask-text.c					\
	solid-pattern-cache-stress.c			\
	source-clip.c					\
	source-clip-scale.c				\
	source-surface-scale-paint.c			\
	spline-decomposition.c				\
	surface-finish-twice.c				\
	surface-pattern.c				\
	surface-pattern-big-scale-down.c		\
	surface-pattern-scale-down.c			\
	surface-pattern-scale-up.c			\
	text-antialias-gray.c				\
	text-antialias-none.c				\
	text-antialias-subpixel.c			\
	text-cache-crash.c				\
	text-glyph-range.c				\
	text-pattern.c					\
	text-rotate.c					\
	text-transform.c				\
	text-zero-len.c					\
	toy-font-face.c					\
	transforms.c					\
	translate-show-surface.c			\
	trap-clip.c					\
	twin.c						\
	twin-antialias-gray.c				\
	twin-antialias-mixed.c				\
	twin-antialias-none.c				\
	twin-antialias-subpixel.c			\
	unantialiased-shapes.c				\
	unbounded-operator.c				\
	user-data.c					\
	user-font.c					\
	user-font-mask.c				\
	user-font-proxy.c				\
	user-font-rescale.c				\
	zero-alpha.c

pthread_test_sources = pthread-show-text.c

ft_font_test_sources = \
	bitmap-font.c \
	ft-font-create-for-ft-face.c \
	ft-show-glyphs-positioning.c \
	ft-show-glyphs-table.c \
	ft-text-vertical-layout-type1.c \
	ft-text-vertical-layout-type3.c \
	ft-text-antialias-none.c

quartz_surface_test_sources = quartz-surface-source.c

glitz_surface_test_sources = glitz-surface-source.c

pdf_surface_test_sources = \
	pdf-features.c \
	pdf-mime-data.c \
	pdf-surface-source.c

ps_surface_test_sources = \
	ps-eps.c \
	ps-features.c \
	ps-surface-source.c

svg_surface_test_sources = \
	svg-surface.c \
	svg-clip.c \
	svg-surface-source.c

test_fallback16_surface_test_sources = \
	test-fallback16-surface-source.c

xlib_surface_test_sources = \
	xlib-expose-event.c \
	xlib-surface.c \
	xlib-surface-source.c

xlib_xrender_surface_test_sources = get-xrender-format.c

multi_page_surface_test_sources = multi-page.c

fallback_resolution_test_sources = fallback-resolution.c

cairo_test_suite_headers = \
	buffer-diff.h \
	cairo-test.h \
	cairo-test-private.h

cairo_test_suite_sources = \
	buffer-diff.c \
	cairo-test.c \
	cairo-test-runner.c
