	; Don't even think of reading this code
	; It was automatically generated by sha512-sse2.pl
	; Which is a perl program used to generate the x86 assember for
	; any of ELF, a.out, COFF, Win32, ...
	; eric <eay@cryptsoft.com>
	; 
	TITLE	sha512-sse2.asm
        .686
.XMM
IF @Version LT 800
XMMWORD STRUCT 16
	DQ  2 dup (?)
XMMWORD ENDS
ENDIF

.model	FLAT
_TEXT$	SEGMENT PAGE 'CODE'

PUBLIC	_sha512_block_sse2

_sha512_block_sse2 PROC NEAR
	push	ebp
	mov	ebp,		esp
	push	ebx
	push	esi
	push	edi
	mov	edx,		DWORD PTR 8[ebp]
	mov	edi,		DWORD PTR 12[ebp]
	call	$L000pic_point
$L000pic_point:
	pop	esi
	lea	esi,		DWORD PTR ($L001K512-$L000pic_point)[esi]
	sub	esp,		320
	and	esp,		-16
	movdqu	xmm0,		XMMWORD PTR [edx]
	movdqu	xmm1,		XMMWORD PTR 16[edx]
	movdqu	xmm2,		XMMWORD PTR 32[edx]
	movdqu	xmm3,		XMMWORD PTR 48[edx]
	ALIGN	8
$L002_chunk_loop:
	movdqa	XMMWORD PTR 256[esp],xmm0
	movdqa	XMMWORD PTR 272[esp],xmm1
	movdqa	XMMWORD PTR 288[esp],xmm2
	movdqa	XMMWORD PTR 304[esp],xmm3
	xor	edx,		edx
	movdq2q	mm0,		xmm0
	movdq2q	mm1,		xmm2
	mov	eax,		DWORD PTR [edx*8+edi]
	mov	ebx,		DWORD PTR 4[edx*8+edi]
	bswap	eax
	bswap	ebx
	mov	DWORD PTR [edx*8+esp],ebx
	mov	DWORD PTR 4[edx*8+esp],eax
	mov	DWORD PTR 128[edx*8+esp],ebx
	mov	DWORD PTR 132[edx*8+esp],eax
	ALIGN	8
$L003_1st_loop:
	mov	eax,		DWORD PTR 8[edx*8+edi]
	mov	ebx,		DWORD PTR 12[edx*8+edi]
	bswap	eax
	bswap	ebx
	mov	DWORD PTR 8[edx*8+esp],ebx
	mov	DWORD PTR 12[edx*8+esp],eax
	mov	DWORD PTR 136[edx*8+esp],ebx
	mov	DWORD PTR 140[edx*8+esp],eax
$L004_1st_looplet:
	movq	mm4,		QWORD PTR 296[esp]
	movq	mm5,		QWORD PTR 304[esp]
	movq	mm6,		QWORD PTR 312[esp]
	movq	mm2,		mm1
	movq	mm3,		mm1
	psrlq	mm2,		14
	psllq	mm3,		23
	movq	mm7,		mm2
	pxor	mm7,		mm3
	psrlq	mm2,		4
	psllq	mm3,		23
	pxor	mm7,		mm2
	pxor	mm7,		mm3
	psrlq	mm2,		23
	psllq	mm3,		4
	pxor	mm7,		mm2
	pxor	mm7,		mm3
	movq	QWORD PTR 296[esp],mm1
	movq	QWORD PTR 304[esp],mm4
	movq	QWORD PTR 312[esp],mm5
	pxor	mm4,		mm5
	pand	mm4,		mm1
	pxor	mm4,		mm5
	paddq	mm7,		mm4
	movq	mm2,		QWORD PTR 264[esp]
	movq	mm3,		QWORD PTR 272[esp]
	movq	mm1,		QWORD PTR 280[esp]
	paddq	mm7,		mm6
	paddq	mm7,		QWORD PTR [edx*8+esi]
	paddq	mm7,		QWORD PTR [edx*8+esp]
	paddq	mm1,		mm7
	movq	mm4,		mm0
	movq	mm5,		mm0
	psrlq	mm4,		28
	psllq	mm5,		25
	movq	mm6,		mm4
	pxor	mm6,		mm5
	psrlq	mm4,		6
	psllq	mm5,		5
	pxor	mm6,		mm4
	pxor	mm6,		mm5
	psrlq	mm4,		5
	psllq	mm5,		6
	pxor	mm6,		mm4
	pxor	mm6,		mm5
	movq	QWORD PTR 264[esp],mm0
	movq	QWORD PTR 272[esp],mm2
	movq	QWORD PTR 280[esp],mm3
	movq	mm4,		mm0
	por	mm0,		mm3
	pand	mm4,		mm3
	pand	mm0,		mm2
	por	mm4,		mm0
	paddq	mm6,		mm4
	movq	mm0,		mm7
	paddq	mm0,		mm6
	inc	edx
	cmp	edx,		15
	jl	$L003_1st_loop
	je	$L004_1st_looplet
	mov	ebx,		edx
	ALIGN	8
$L005_2nd_loop:
	and	edx,		15
	movdqu	xmm0,		XMMWORD PTR 8[edx*8+esp]
	movdqa	xmm2,		xmm0
	movdqa	xmm3,		xmm0
	psrlq	xmm2,		1
	psllq	xmm3,		56
	movdqa	xmm0,		xmm2
	pxor	xmm0,		xmm3
	psrlq	xmm2,		6
	psllq	xmm3,		7
	pxor	xmm0,		xmm2
	pxor	xmm0,		xmm3
	psrlq	xmm2,		1
	pxor	xmm0,		xmm2
	movdqa	xmm1,		XMMWORD PTR 112[edx*8+esp]
	movdqa	xmm4,		xmm1
	movdqa	xmm5,		xmm1
	psrlq	xmm4,		6
	psllq	xmm5,		3
	movdqa	xmm1,		xmm4
	pxor	xmm1,		xmm5
	psrlq	xmm4,		13
	psllq	xmm5,		42
	pxor	xmm1,		xmm4
	pxor	xmm1,		xmm5
	psrlq	xmm4,		42
	pxor	xmm1,		xmm4
	movdqu	xmm6,		XMMWORD PTR 72[edx*8+esp]
	paddq	xmm0,		xmm1
	paddq	xmm0,		xmm6
	paddq	xmm0,		XMMWORD PTR [edx*8+esp]
	movdqa	XMMWORD PTR [edx*8+esp],xmm0
	movdqa	XMMWORD PTR 128[edx*8+esp],xmm0
	movq	mm4,		QWORD PTR 296[esp]
	movq	mm5,		QWORD PTR 304[esp]
	movq	mm6,		QWORD PTR 312[esp]
	movq	mm2,		mm1
	movq	mm3,		mm1
	psrlq	mm2,		14
	psllq	mm3,		23
	movq	mm7,		mm2
	pxor	mm7,		mm3
	psrlq	mm2,		4
	psllq	mm3,		23
	pxor	mm7,		mm2
	pxor	mm7,		mm3
	psrlq	mm2,		23
	psllq	mm3,		4
	pxor	mm7,		mm2
	pxor	mm7,		mm3
	movq	QWORD PTR 296[esp],mm1
	movq	QWORD PTR 304[esp],mm4
	movq	QWORD PTR 312[esp],mm5
	pxor	mm4,		mm5
	pand	mm4,		mm1
	pxor	mm4,		mm5
	paddq	mm7,		mm4
	movq	mm2,		QWORD PTR 264[esp]
	movq	mm3,		QWORD PTR 272[esp]
	movq	mm1,		QWORD PTR 280[esp]
	paddq	mm7,		mm6
	paddq	mm7,		QWORD PTR [ebx*8+esi]
	paddq	mm7,		QWORD PTR [edx*8+esp]
	paddq	mm1,		mm7
	movq	mm4,		mm0
	movq	mm5,		mm0
	psrlq	mm4,		28
	psllq	mm5,		25
	movq	mm6,		mm4
	pxor	mm6,		mm5
	psrlq	mm4,		6
	psllq	mm5,		5
	pxor	mm6,		mm4
	pxor	mm6,		mm5
	psrlq	mm4,		5
	psllq	mm5,		6
	pxor	mm6,		mm4
	pxor	mm6,		mm5
	movq	QWORD PTR 264[esp],mm0
	movq	QWORD PTR 272[esp],mm2
	movq	QWORD PTR 280[esp],mm3
	movq	mm4,		mm0
	por	mm0,		mm3
	pand	mm4,		mm3
	pand	mm0,		mm2
	por	mm4,		mm0
	paddq	mm6,		mm4
	movq	mm0,		mm7
	paddq	mm0,		mm6
	inc	ebx
	inc	edx
	movq	mm4,		QWORD PTR 296[esp]
	movq	mm5,		QWORD PTR 304[esp]
	movq	mm6,		QWORD PTR 312[esp]
	movq	mm2,		mm1
	movq	mm3,		mm1
	psrlq	mm2,		14
	psllq	mm3,		23
	movq	mm7,		mm2
	pxor	mm7,		mm3
	psrlq	mm2,		4
	psllq	mm3,		23
	pxor	mm7,		mm2
	pxor	mm7,		mm3
	psrlq	mm2,		23
	psllq	mm3,		4
	pxor	mm7,		mm2
	pxor	mm7,		mm3
	movq	QWORD PTR 296[esp],mm1
	movq	QWORD PTR 304[esp],mm4
	movq	QWORD PTR 312[esp],mm5
	pxor	mm4,		mm5
	pand	mm4,		mm1
	pxor	mm4,		mm5
	paddq	mm7,		mm4
	movq	mm2,		QWORD PTR 264[esp]
	movq	mm3,		QWORD PTR 272[esp]
	movq	mm1,		QWORD PTR 280[esp]
	paddq	mm7,		mm6
	paddq	mm7,		QWORD PTR [ebx*8+esi]
	paddq	mm7,		QWORD PTR [edx*8+esp]
	paddq	mm1,		mm7
	movq	mm4,		mm0
	movq	mm5,		mm0
	psrlq	mm4,		28
	psllq	mm5,		25
	movq	mm6,		mm4
	pxor	mm6,		mm5
	psrlq	mm4,		6
	psllq	mm5,		5
	pxor	mm6,		mm4
	pxor	mm6,		mm5
	psrlq	mm4,		5
	psllq	mm5,		6
	pxor	mm6,		mm4
	pxor	mm6,		mm5
	movq	QWORD PTR 264[esp],mm0
	movq	QWORD PTR 272[esp],mm2
	movq	QWORD PTR 280[esp],mm3
	movq	mm4,		mm0
	por	mm0,		mm3
	pand	mm4,		mm3
	pand	mm0,		mm2
	por	mm4,		mm0
	paddq	mm6,		mm4
	movq	mm0,		mm7
	paddq	mm0,		mm6
	inc	ebx
	inc	edx
	cmp	ebx,		80
	jl	$L005_2nd_loop
	mov	edx,		DWORD PTR 8[ebp]
	movq	QWORD PTR 256[esp],mm0
	movq	QWORD PTR 288[esp],mm1
	movdqu	xmm0,		XMMWORD PTR [edx]
	movdqu	xmm1,		XMMWORD PTR 16[edx]
	movdqu	xmm2,		XMMWORD PTR 32[edx]
	movdqu	xmm3,		XMMWORD PTR 48[edx]
	paddq	xmm0,		XMMWORD PTR 256[esp]
	paddq	xmm1,		XMMWORD PTR 272[esp]
	paddq	xmm2,		XMMWORD PTR 288[esp]
	paddq	xmm3,		XMMWORD PTR 304[esp]
	movdqu	XMMWORD PTR [edx],xmm0
	movdqu	XMMWORD PTR 16[edx],xmm1
	movdqu	XMMWORD PTR 32[edx],xmm2
	movdqu	XMMWORD PTR 48[edx],xmm3
	add	edi,		128
	dec	DWORD PTR 16[ebp]
	jnz	$L002_chunk_loop
	emms
	mov	edi,		DWORD PTR [ebp-12]
	mov	esi,		DWORD PTR [ebp-8]
	mov	ebx,		DWORD PTR [ebp-4]
	leave
	ret
	ALIGN	64
$L001K512:
	DD	3609767458,1116352408
	DD	602891725,1899447441
	DD	3964484399,3049323471
	DD	2173295548,3921009573
	DD	4081628472,961987163
	DD	3053834265,1508970993
	DD	2937671579,2453635748
	DD	3664609560,2870763221
	DD	2734883394,3624381080
	DD	1164996542,310598401
	DD	1323610764,607225278
	DD	3590304994,1426881987
	DD	4068182383,1925078388
	DD	991336113,2162078206
	DD	633803317,2614888103
	DD	3479774868,3248222580
	DD	2666613458,3835390401
	DD	944711139,4022224774
	DD	2341262773,264347078
	DD	2007800933,604807628
	DD	1495990901,770255983
	DD	1856431235,1249150122
	DD	3175218132,1555081692
	DD	2198950837,1996064986
	DD	3999719339,2554220882
	DD	766784016,2821834349
	DD	2566594879,2952996808
	DD	3203337956,3210313671
	DD	1034457026,3336571891
	DD	2466948901,3584528711
	DD	3758326383,113926993
	DD	168717936,338241895
	DD	1188179964,666307205
	DD	1546045734,773529912
	DD	1522805485,1294757372
	DD	2643833823,1396182291
	DD	2343527390,1695183700
	DD	1014477480,1986661051
	DD	1206759142,2177026350
	DD	344077627,2456956037
	DD	1290863460,2730485921
	DD	3158454273,2820302411
	DD	3505952657,3259730800
	DD	106217008,3345764771
	DD	3606008344,3516065817
	DD	1432725776,3600352804
	DD	1467031594,4094571909
	DD	851169720,275423344
	DD	3100823752,430227734
	DD	1363258195,506948616
	DD	3750685593,659060556
	DD	3785050280,883997877
	DD	3318307427,958139571
	DD	3812723403,1322822218
	DD	2003034995,1537002063
	DD	3602036899,1747873779
	DD	1575990012,1955562222
	DD	1125592928,2024104815
	DD	2716904306,2227730452
	DD	442776044,2361852424
	DD	593698344,2428436474
	DD	3733110249,2756734187
	DD	2999351573,3204031479
	DD	3815920427,3329325298
	DD	3928383900,3391569614
	DD	566280711,3515267271
	DD	3454069534,3940187606
	DD	4000239992,4118630271
	DD	1914138554,116418474
	DD	2731055270,174292421
	DD	3203993006,289380356
	DD	320620315,460393269
	DD	587496836,685471733
	DD	1086792851,852142971
	DD	365543100,1017036298
	DD	2618297676,1126000580
	DD	3409855158,1288033470
	DD	4234509866,1501505948
	DD	987167468,1607167915
	DD	1246189591,1816402316
_sha512_block_sse2 ENDP
_TEXT$	ENDS
END
