top_srcdir = ../..
include $(top_srcdir)/build/Makefile.win32.common

CFLAGS += -I../../src

SOURCES = \
	lpyramid.c \
	pdiff.c \
	$(NULL)

OBJECTS = $(subst .c,.obj,$(SOURCES))

all: pdiff.lib

pdiff.lib: $(OBJECTS)
	lib -NOLOGO -OUT:$@ $(OBJECTS)

%.obj: %.c
	@$(CC) $(CFLAGS) -DCAIRO_WIN32_STATIC_BUILD=1 -c -Fo"$@" $<
